# Generated by Django 5.2.8 on 2026-01-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
