# Generated by Django 5.2.8 on 2026-02-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('authority_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'موفق'), (2, 'ناموفق'), (3, 'در انتظار پرداخت')], default=3)),
                ('response_json', models.JSONField(blank=True, default=dict, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
